script: ./travis-build.sh
jdk:
- openjdk7
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
 env:
  global:
    secure: qdIkgqH7+I+A0rSjXLWJnVb1qtWkmd2SfFwSzchpEhYpKC0TtfvxsfqBaCha95L926YZna050tWkC9Fq33prxsyInqd4VRsPuNgp3KEsW+4sUd5LhDW6Y5luCFkB/RStMXSSuUv7NHxmjG6dsg4A/lV53tWv1xMhNZknTmYDBEM=
